// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjtNO1qdtTAJ3EfQPgnlq62Ihlo2u5ZkE',
    appId: '1:870296768276:web:2a9feff916b035cc1d3c01',
    messagingSenderId: '870296768276',
    projectId: 'acaicravinhos',
    authDomain: 'acaicravinhos.firebaseapp.com',
    storageBucket: 'acaicravinhos.firebasestorage.app',
    measurementId: 'G-T6DN7138EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-yWfCBwNtx3hR5SqtD43FjcKPYzfaQ40',
    appId: '1:870296768276:android:7380e7b601ef27c11d3c01',
    messagingSenderId: '870296768276',
    projectId: 'acaicravinhos',
    storageBucket: 'acaicravinhos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD26W9jvWeyr-0MrQg6vrLLhVhrYrbSGbY',
    appId: '1:870296768276:ios:2f21738764c097c91d3c01',
    messagingSenderId: '870296768276',
    projectId: 'acaicravinhos',
    storageBucket: 'acaicravinhos.firebasestorage.app',
    iosBundleId: 'com.maniadeacai.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD26W9jvWeyr-0MrQg6vrLLhVhrYrbSGbY',
    appId: '1:870296768276:ios:2f21738764c097c91d3c01',
    messagingSenderId: '870296768276',
    projectId: 'acaicravinhos',
    storageBucket: 'acaicravinhos.firebasestorage.app',
    iosBundleId: 'com.maniadeacai.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjtNO1qdtTAJ3EfQPgnlq62Ihlo2u5ZkE',
    appId: '1:870296768276:web:91dd5b3707b3846f1d3c01',
    messagingSenderId: '870296768276',
    projectId: 'acaicravinhos',
    authDomain: 'acaicravinhos.firebaseapp.com',
    storageBucket: 'acaicravinhos.firebasestorage.app',
    measurementId: 'G-ZF1R0CZCBT',
  );

}